version: "3.7"

services:
    ner-api:
        build:
            dockerfile: Dockerfile
            context: .
        image: ner-api
        container_name: ner-api
        environment:
            LOG_LEVEL: ${LOG_LEVEL}
            MODEL_PATH: ${MODEL_PATH}
            TF_PARALLEL_CORES: ${TF_PARALLEL_CORES}
        networks:
            - ner-net
        volumes:
            - .:/app/
        ports:
            - "8084:80"
        command: uvicorn ner_api.main:app --host 0.0.0.0 --port 80 --log-level ${LOG_LEVEL} --reload


networks:
    ner-net:
        name: ner-net
